using BaseProject.Data;
using BaseProject.Models.Contracts;
using BaseProject.Models.Contracts.Dtos;
using BaseProject.Models.Contracts.Responses;
using BaseProject.Models.Data;
using BaseProject.Models.Extensions;
using BaseProject.Models.Mappers;
using Microsoft.EntityFrameworkCore;

namespace BaseProject.Services.Data;

public class JustificationService(ProjectDbContext context)
{
    public IOrderedQueryable<Justification> GetAll(JustificationFilter filter)
    {
        var query = context.Justifications.AsQueryable();
        var search = filter.Search;
        var lastSync = filter.LastSync;
        if (!string.IsNullOrEmpty(search))
        {
            query = query.Where(x => x.Name.Contains(search));
        }
        
        if (lastSync.HasValue)
        {
             query = query.Where(x => x.UpdatedAt > lastSync.Value);
        }

        return query.OrderBy(x => x.Id);
    }
    
    public async Task<ResultResponse> GetById(int id)
    {
        var justification = await context.Justifications.FindAsync(id);
        if (justification == null)
        {
            return new ResultResponse.Error("Justification not found");
        }
        return new ResultResponse.Success<Justification>(justification);
    }
    
    public async Task<ResultResponse> Create(JustificationDto dto)
    {
        var justification = dto.ToEntity();
        // Since Id is likely Identity, we don't check for existence by Id prior to insertion unless it's not identity.
        // Assuming Id is auto-generated by DB. If manual, we should check. 
        // Based on model 'DatabaseGenerated' is not explicitly set to None, so default is usually Identity for int Key.
        
        await context.Justifications.AddAsync(justification);
        await context.SaveChangesAsync();
        
        return new ResultResponse.Success<Justification>(justification);
    }
    
    public async Task<ResultResponse> Update(int id, JustificationDto dto)
    {
        var existing = await context.Justifications.FindAsync(id);
        if (existing == null)
        {
            return new ResultResponse.Error("Justification not found");
        }
        
        existing.Name = dto.Name;
        
        context.Justifications.Update(existing);
        await context.SaveChangesAsync();
        
        return new ResultResponse.Success<Justification>(existing);
    }
    
    public async Task<ResultResponse> Delete(int id)
    {
        var existing = await context.Justifications.FindAsync(id);
        if (existing == null)
        {
            return new ResultResponse.Error("Justification not found");
        }
        existing.Delete(existing.DeletedAt == null);
        await context.SaveChangesAsync();
        
        return new ResultResponse.Success<Justification>(existing);
    }
    
    public async Task<ResultResponse> Destroy(int id)
    {
        var existing = await context.Justifications.FindAsync(id);
        if (existing == null)
        {
            return new ResultResponse.Error("Justification not found");
        }
        context.Justifications.Remove(existing);
        await context.SaveChangesAsync();
        
        return new ResultResponse.Success<string>("Justification deleted");
    }
}
