// <auto-generated />
using System;
using BaseProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseProject.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260414161310_UpdateProduct")]
    partial class UpdateProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("BaseProject.Models.Data.Aisle", b =>
                {
                    b.Property<string>("WareHouseCode")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRack")
                        .HasColumnType("INTEGER");

                    b.HasKey("WareHouseCode", "Number");

                    b.ToTable("Aisle");
                });

            modelBuilder.Entity("BaseProject.Models.Data.BarCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeleteAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("BarCode");
                });

            modelBuilder.Entity("BaseProject.Models.Data.BranchOffice", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeleteAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("BranchOffice");
                });

            modelBuilder.Entity("BaseProject.Models.Data.Customer", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeleteAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("BaseProject.Models.Data.Justification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreateAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeleteAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Justification");
                });

            modelBuilder.Entity("BaseProject.Models.Data.Product", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeleteAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("BaseProject.Models.Data.Provider", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeleteAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("BaseProject.Models.Data.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreateAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeleteAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Invoice")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Sync")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncUser")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Transference")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransferenceUser")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("BaseProject.Models.Data.PurchaseProduct", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("ItemCode")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("Adjustment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountDispatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountRequest")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Justify")
                        .HasMaxLength(150)
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductInfoCode")
                        .HasColumnType("TEXT");

                    b.HasKey("PurchaseOrderId", "ItemCode");

                    b.HasIndex("ProductInfoCode");

                    b.ToTable("PurchaseProduct");
                });

            modelBuilder.Entity("BaseProject.Models.Data.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelAccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("BaseProject.Models.Data.SaleOrder", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreateAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeleteAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Sync")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncUser")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Transference")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransferenceUser")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode");

                    b.HasIndex("UserId");

                    b.ToTable("SaleOrder");
                });

            modelBuilder.Entity("BaseProject.Models.Data.SaleOrderLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InputA")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InputB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputC")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeLog")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaleOrderLog");
                });

            modelBuilder.Entity("BaseProject.Models.Data.SaleOrderStatus", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("IdOrder");

                    b.HasIndex("UserId");

                    b.ToTable("SaleOrderStatus");
                });

            modelBuilder.Entity("BaseProject.Models.Data.SaleProduct", b =>
                {
                    b.Property<int>("SaleOrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("ItemCode")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("Adjustment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountDispatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountRequest")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Justify")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductInfoCode")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TimeToExpire")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("SaleOrderId", "ItemCode");

                    b.HasIndex("ProductInfoCode");

                    b.ToTable("SaleProduct");
                });

            modelBuilder.Entity("BaseProject.Models.Data.SaleProductSerial", b =>
                {
                    b.Property<int>("SaleOrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("ItemCode")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Serial")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("SaleOrderId", "ItemCode", "Serial");

                    b.ToTable("SaleProductSerial");
                });

            modelBuilder.Entity("BaseProject.Models.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BaseProject.Models.Data.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expired")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSession");
                });

            modelBuilder.Entity("BaseProject.Models.Data.WareHouse", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeleteAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("WareHouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BaseProject.Models.Data.Aisle", b =>
                {
                    b.HasOne("BaseProject.Models.Data.WareHouse", "WareHouseInfo")
                        .WithMany("Aisles")
                        .HasForeignKey("WareHouseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WareHouseInfo");
                });

            modelBuilder.Entity("BaseProject.Models.Data.PurchaseProduct", b =>
                {
                    b.HasOne("BaseProject.Models.Data.Product", "ProductInfo")
                        .WithMany()
                        .HasForeignKey("ProductInfoCode");

                    b.HasOne("BaseProject.Models.Data.PurchaseOrder", null)
                        .WithMany("Products")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductInfo");
                });

            modelBuilder.Entity("BaseProject.Models.Data.SaleOrder", b =>
                {
                    b.HasOne("BaseProject.Models.Data.Customer", "CustomerInfo")
                        .WithMany()
                        .HasForeignKey("CustomerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseProject.Models.Data.User", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CustomerInfo");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("BaseProject.Models.Data.SaleOrderStatus", b =>
                {
                    b.HasOne("BaseProject.Models.Data.User", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("BaseProject.Models.Data.SaleProduct", b =>
                {
                    b.HasOne("BaseProject.Models.Data.Product", "ProductInfo")
                        .WithMany()
                        .HasForeignKey("ProductInfoCode");

                    b.HasOne("BaseProject.Models.Data.SaleOrder", null)
                        .WithMany("Products")
                        .HasForeignKey("SaleOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductInfo");
                });

            modelBuilder.Entity("BaseProject.Models.Data.SaleProductSerial", b =>
                {
                    b.HasOne("BaseProject.Models.Data.SaleOrder", null)
                        .WithMany("ProductSerials")
                        .HasForeignKey("SaleOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaseProject.Models.Data.UserSession", b =>
                {
                    b.HasOne("BaseProject.Models.Data.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("BaseProject.Models.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BaseProject.Models.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BaseProject.Models.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("BaseProject.Models.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseProject.Models.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BaseProject.Models.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaseProject.Models.Data.PurchaseOrder", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BaseProject.Models.Data.SaleOrder", b =>
                {
                    b.Navigation("ProductSerials");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("BaseProject.Models.Data.User", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("BaseProject.Models.Data.WareHouse", b =>
                {
                    b.Navigation("Aisles");
                });
#pragma warning restore 612, 618
        }
    }
}
